spring.application.name=bookvault-backend

# Removed PostgreSQL, using Firebase Firestore instead

# Server Port (Render dynamically assigns PORT)
server.port=${PORT:8080}

# Mail Service Configuration
# In Render, you will set the MAIL_SERVICE_URL environment variable.
mail-service.url=${MAIL_SERVICE_URL:https://mail-service-latest-cgm4.onrender.com/api/v1/mail}
mail-service.api-key=${MAIL_SERVICE_API_KEY:BV-SECURE-API-PROD-2026-X7Y2}
mail-service.secret-key=${MAIL_SERVICE_SECRET_KEY:BV-SECURE-SECRET-PROD-VAULT-Q9P4-ENCRYPTED}
mail-service.sender=${MAIL_SERVICE_SENDER:generatedmailservice@gmail.com}
mail-service.admin-email=${ADMIN_EMAIL:hemanth.nitm@gmail.com}

# Firebase Auth Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/bookvault-c0995
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Google Drive Configuration
google.drive.folder.id=1rD91p8MflkyiXMFdchl06JlxpvEJtnNW
